services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hms
    ports:
      - "5432:5432"
    volumes:
      - hms_pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hms"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: docker.io/library/redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - hms_redis_data:/data

volumes:
  hms_pg_data:
  hms_redis_data:
